/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BILL.java
 *
 * Created on Apr 5, 2012, 7:46:50 PM
 */
package miniproj;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Anjana
 */
public class BILL extends javax.swing.JFrame {
Connection con;
Statement stmt;
ResultSet rs;
    /** Creates new form BILL */
    public BILL() {
        initComponents();
         try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            JOptionPane.showMessageDialog(this, "Driver Loaded Succesfully!");
        }
        catch(ClassNotFoundException E)
        {
                JOptionPane.showMessageDialog(this, "Driver Not Loaded");
        }
        try
        {
            con=DriverManager.getConnection("jdbc:odbc:dsn","system","orcl");
            JOptionPane.showMessageDialog(this, "Connection Established!");
        }
        catch(SQLException E)
        {JOptionPane.showMessageDialog(this, "Connection Not Established");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        broomr = new javax.swing.JTextField();
        broomnoofdays = new javax.swing.JTextField();
        brooma = new javax.swing.JTextField();
        bvaletr = new javax.swing.JTextField();
        bvaletq = new javax.swing.JTextField();
        bvaleta = new javax.swing.JTextField();
        btear = new javax.swing.JTextField();
        bteaq = new javax.swing.JTextField();
        bteaa = new javax.swing.JTextField();
        binternetr = new javax.swing.JTextField();
        binternetq = new javax.swing.JTextField();
        binterneta = new javax.swing.JTextField();
        btelephoner = new javax.swing.JTextField();
        btelephoneq = new javax.swing.JTextField();
        btelephonea = new javax.swing.JTextField();
        bnewspaperr = new javax.swing.JTextField();
        bnewspaperq = new javax.swing.JTextField();
        bnewspapera = new javax.swing.JTextField();
        bcarr = new javax.swing.JTextField();
        bcarq = new javax.swing.JTextField();
        bcara = new javax.swing.JTextField();
        blaundryr = new javax.swing.JTextField();
        blaundryq = new javax.swing.JTextField();
        blaundrya = new javax.swing.JTextField();
        bbusr = new javax.swing.JTextField();
        bbusq = new javax.swing.JTextField();
        bbusa = new javax.swing.JTextField();
        bparkr = new javax.swing.JTextField();
        bparkq = new javax.swing.JTextField();
        bparka = new javax.swing.JTextField();
        bparlourr = new javax.swing.JTextField();
        bparlourq = new javax.swing.JTextField();
        bparloura = new javax.swing.JTextField();
        bfooda = new javax.swing.JTextField();
        btotal = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        billno = new javax.swing.JTextField();
        bguestname = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        bguestid = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        bbill = new javax.swing.JButton();
        bclear = new javax.swing.JButton();
        breturn = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        broomnoofrooms = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bill");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BILL");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BILL NO");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GUEST ID");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GUEST NAME");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ROOM CHARGES");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SERVICES");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FOOD CHARGES");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" 1");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" 2");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" 3");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" 4");

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" 5");

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" 6");

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(" 7");

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" 8");

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" 9");

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("VALET");

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("TEA AND COFFEE");

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("INTERNET");

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("TELEPHONE");

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("NEWSPAPER");

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("CAR SERVICES");

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("LAUNDRY");

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("BUS SERVICES");

        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("PARKING");

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("BEAUTY PARLOUR");

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("RATE");

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("QUANTITY");

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("AMOUNT");

        broomr.setForeground(new java.awt.Color(51, 153, 255));

        broomnoofdays.setForeground(new java.awt.Color(51, 153, 255));
        broomnoofdays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                broomnoofdaysActionPerformed(evt);
            }
        });

        brooma.setForeground(new java.awt.Color(51, 153, 255));

        bvaletr.setForeground(new java.awt.Color(51, 153, 255));

        bvaletq.setForeground(new java.awt.Color(51, 153, 255));

        bvaleta.setForeground(new java.awt.Color(51, 153, 255));

        btear.setForeground(new java.awt.Color(51, 153, 255));

        bteaq.setForeground(new java.awt.Color(51, 153, 255));
        bteaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteaqActionPerformed(evt);
            }
        });

        bteaa.setForeground(new java.awt.Color(51, 153, 255));

        binternetr.setForeground(new java.awt.Color(51, 153, 255));

        binternetq.setForeground(new java.awt.Color(51, 153, 255));
        binternetq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binternetqActionPerformed(evt);
            }
        });

        binterneta.setForeground(new java.awt.Color(51, 153, 255));

        btelephoner.setForeground(new java.awt.Color(51, 153, 255));

        btelephoneq.setForeground(new java.awt.Color(51, 153, 255));
        btelephoneq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btelephoneqActionPerformed(evt);
            }
        });

        btelephonea.setForeground(new java.awt.Color(51, 153, 255));

        bnewspaperr.setForeground(new java.awt.Color(51, 153, 255));

        bnewspaperq.setForeground(new java.awt.Color(51, 153, 255));

        bnewspapera.setForeground(new java.awt.Color(51, 153, 255));
        bnewspapera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnewspaperaActionPerformed(evt);
            }
        });

        bcarr.setForeground(new java.awt.Color(51, 153, 255));

        bcarq.setForeground(new java.awt.Color(51, 153, 255));

        bcara.setForeground(new java.awt.Color(51, 153, 255));

        blaundryr.setForeground(new java.awt.Color(51, 153, 255));

        blaundryq.setForeground(new java.awt.Color(51, 153, 255));
        blaundryq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blaundryqActionPerformed(evt);
            }
        });

        blaundrya.setForeground(new java.awt.Color(51, 153, 255));

        bbusr.setForeground(new java.awt.Color(51, 153, 255));

        bbusq.setForeground(new java.awt.Color(51, 153, 255));

        bbusa.setForeground(new java.awt.Color(51, 153, 255));

        bparkr.setForeground(new java.awt.Color(51, 153, 255));

        bparkq.setForeground(new java.awt.Color(51, 153, 255));
        bparkq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bparkqActionPerformed(evt);
            }
        });

        bparka.setForeground(new java.awt.Color(51, 153, 255));
        bparka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bparkaActionPerformed(evt);
            }
        });

        bparlourr.setForeground(new java.awt.Color(51, 153, 255));

        bparlourq.setForeground(new java.awt.Color(51, 153, 255));

        bparloura.setForeground(new java.awt.Color(51, 153, 255));
        bparloura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bparlouraActionPerformed(evt);
            }
        });

        bfooda.setForeground(new java.awt.Color(51, 153, 255));

        btotal.setForeground(new java.awt.Color(51, 153, 255));

        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("*");

        jLabel34.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("*");

        jLabel35.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("*");

        jLabel36.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("*");

        jLabel37.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("*");

        jLabel38.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("*");

        jLabel39.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("*");

        jLabel40.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("*");

        jLabel41.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("*");

        jLabel42.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("*");

        jLabel43.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("*");

        jLabel44.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("=");

        jLabel45.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("=");

        jLabel46.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("=");

        jLabel47.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("=");

        jLabel48.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("=");

        jLabel49.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("=");

        jLabel50.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("=");

        jLabel51.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("=");

        jLabel52.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("=");

        jLabel53.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("=");

        jLabel54.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("=");

        jLabel55.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("=");

        jLabel56.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("=");

        billno.setForeground(new java.awt.Color(51, 153, 255));

        bguestname.setForeground(new java.awt.Color(51, 153, 255));
        bguestname.setText(" ");
        bguestname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bguestnameActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("10");

        bguestid.setForeground(new java.awt.Color(51, 153, 255));
        bguestid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bguestidActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("GRAND TOTAL");

        bbill.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        bbill.setForeground(new java.awt.Color(0, 153, 204));
        bbill.setText("GENERATE BILL & CHECK OUT");
        bbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbillActionPerformed(evt);
            }
        });

        bclear.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        bclear.setForeground(new java.awt.Color(0, 153, 204));
        bclear.setText("CLEAR");
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });

        breturn.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        breturn.setForeground(new java.awt.Color(0, 153, 204));
        breturn.setText("RETURN TO CHECK IN");
        breturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breturnActionPerformed(evt);
            }
        });

        jLabel57.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("*");

        broomnoofrooms.setForeground(new java.awt.Color(51, 153, 255));
        broomnoofrooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                broomnoofroomsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bguestname, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bguestid, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(billno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bbill, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bclear, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(blaundryr, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(bparlourr, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(binternetr, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(bnewspaperr, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(btelephoner, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(bcarr, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(bbusr, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(bparkr, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(btear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(bvaletr, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(broomr, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bparlourq, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(bparkq, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(bbusq, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(blaundryq, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(bcarq, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(bnewspaperq, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(btelephoneq, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(binternetq, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(bteaq, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(bvaletq, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(broomnoofdays, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(broomnoofrooms, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                                    .addComponent(jLabel56, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                                    .addComponent(jLabel54, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                                    .addComponent(jLabel53, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                                    .addComponent(jLabel51, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                                    .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                                    .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                                    .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                                    .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                                    .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                                    .addComponent(jLabel52, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blaundrya, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bvaleta)
                                .addComponent(brooma, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btotal)
                                .addComponent(bparloura, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                .addComponent(bparka)
                                .addComponent(bfooda)
                                .addComponent(bteaa, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addComponent(bbusa, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                .addComponent(bcara)
                                .addComponent(binterneta, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                .addComponent(btelephonea)
                                .addComponent(bnewspapera))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(breturn)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addGap(286, 286, 286))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(billno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(bguestid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(bguestname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(broomr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(broomnoofdays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44)
                    .addComponent(brooma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57)
                    .addComponent(broomnoofrooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(bvaletr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(bvaleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(bvaletq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(btear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(bteaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(bteaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(binternetr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(binterneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(binternetq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btelephoner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel22)
                    .addComponent(btelephonea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(btelephoneq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnewspaperr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel23)
                    .addComponent(bnewspapera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(bnewspaperq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bcarr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)
                        .addComponent(bcara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel38)
                        .addComponent(bcarq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel50))
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(blaundryr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel39)
                        .addComponent(blaundryq, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel51))
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blaundrya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(bbusr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(bbusa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(bbusq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(bparkr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27)
                        .addComponent(jLabel41))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bparkq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel53)
                        .addComponent(bparka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bparlourr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel28)
                    .addComponent(jLabel42)
                    .addComponent(bparlourq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54)
                    .addComponent(bparloura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel55)
                            .addComponent(bfooda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel56)
                            .addComponent(btotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breturn)
                    .addComponent(bbill)
                    .addComponent(bclear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void binternetqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binternetqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_binternetqActionPerformed

    private void bteaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteaqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bteaqActionPerformed

    private void broomnoofdaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_broomnoofdaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_broomnoofdaysActionPerformed

    private void blaundryqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blaundryqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blaundryqActionPerformed

    private void bparkqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bparkqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bparkqActionPerformed

    private void bnewspaperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnewspaperaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnewspaperaActionPerformed

    private void bguestnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bguestnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bguestnameActionPerformed

    private void bguestidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bguestidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bguestidActionPerformed

    private void bparlouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bparlouraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bparlouraActionPerformed

    private void btelephoneqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btelephoneqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btelephoneqActionPerformed

    private void bparkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bparkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bparkaActionPerformed

    private void bbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbillActionPerformed
        // TODO add your handling code here:
        try
        {
            String sql=("begin food_charges("+bguestid.getText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            //clear();
           // JOptionPane.showMessageDialog(this,"Procedure called Successfully!!");
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            String sql=("begin room_rent("+bguestid.getText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            //clear();
          //  JOptionPane.showMessageDialog(this,"Procedure called Successfully!!");
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            String sql=("begin total_charges("+bguestid.getText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            //clear();
            //JOptionPane.showMessageDialog(this,"Procedure called Successfully!!");
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
        stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from guest where id="+bguestid.getText()+"");
            rs.first();
            bguestname.setText(rs.getString(2));
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
        stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select noofdays("+bguestid.getText()+") from dual");
            rs.first();
            broomnoofdays.setText(rs.getString(1));
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
        stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from bill where guestid="+bguestid.getText()+"");
            rs.first();
            billno.setText(rs.getString(1));
            broomnoofrooms.setText(rs.getString(3));
            brooma.setText(rs.getString(4));
            bfooda.setText(rs.getString(5));
            btotal.setText(rs.getString(6));
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
        stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select r.rate from room r join allotted a on( r.roomno=a.roomno ) join guest g on (g.id=a.guestid) where g.id="+bguestid.getText()+" and r.status='occupied'");
            rs.first();
            broomr.setText(rs.getString(1));
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from uses where guestid = "+bguestid.getText()+" and facilityid=1");
            rs.first();
            bvaletq.setText(rs.getString(3));
            bvaleta.setText(rs.getString(4));
            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from uses where guestid ="+bguestid.getText()+" and facilityid=2");
            rs.first();
            bteaq.setText(rs.getString(3));
            bteaa.setText(rs.getString(4));
            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from uses where guestid ="+bguestid.getText()+" and facilityid=3");
            rs.first();
            binternetq.setText(rs.getString(3));
            binterneta.setText(rs.getString(4));
            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from uses where guestid ="+bguestid.getText()+" and facilityid=4");
            rs.first();
            btelephoneq.setText(rs.getString(3));
            btelephonea.setText(rs.getString(4));
            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from uses where guestid ="+bguestid.getText()+" and facilityid=5");
            rs.first();
            bnewspaperq.setText(rs.getString(3));
            bnewspapera.setText(rs.getString(4));
            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from uses where guestid ="+bguestid.getText()+" and facilityid=6");
            rs.first();
            bcarq.setText(rs.getString(3));
            bcara.setText(rs.getString(4));
            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from uses where guestid ="+bguestid.getText()+" and facilityid=7");
            rs.first();
            blaundryq.setText(rs.getString(3));
            blaundrya.setText(rs.getString(4));
            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from uses where guestid ="+bguestid.getText()+" and facilityid=8");
            rs.first();
            bbusq.setText(rs.getString(3));
            bbusa.setText(rs.getString(4));
            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from uses where guestid ="+bguestid.getText()+" and facilityid=9");
            rs.first();
            bparkq.setText(rs.getString(3));
            bparka.setText(rs.getString(4));
            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from uses where guestid ="+bguestid.getText()+" and facilityid=10");
            rs.first();
            bparlourq.setText(rs.getString(3));
            bparloura.setText(rs.getString(4));
            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from facilities where id=1");
            rs.first();
            bvaletr.setText(rs.getString(3));            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from facilities where id=2");
            rs.first();
            btear.setText(rs.getString(3));            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from facilities where id=3");
            rs.first();
            binternetr.setText(rs.getString(3));            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from facilities where id=4");
            rs.first();
            btelephoner.setText(rs.getString(3));            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from facilities where id=5");
            rs.first();
            bnewspaperr.setText(rs.getString(3));            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from facilities where id=6");
            rs.first();
            bcarr.setText(rs.getString(3));            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from facilities where id=7");
            rs.first();
            blaundryr.setText(rs.getString(3));            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from facilities where id=8");
            rs.first();
            bbusr.setText(rs.getString(3));            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from facilities where id=9");
            rs.first();
            bparkr.setText(rs.getString(3));            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs=stmt.executeQuery("select * from facilities where id=10");
            rs.first();
            bparlourr.setText(rs.getString(3));            
        }
         catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            String sql=("begin before_exit("+bguestid.getText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            //clear();
            JOptionPane.showMessageDialog(this,"Updated room as unoccupied Successfully!!");
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }     
      
        
    }//GEN-LAST:event_bbillActionPerformed

    private void breturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breturnActionPerformed
        // TODO add your handling code here:
        checkin c = new checkin();
        c.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_breturnActionPerformed

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
        // TODO add your handling code here:
       billno.setText("");
       bguestid.setText("");
       bguestname.setText("");
       broomr.setText("");
       broomnoofdays.setText("");
       broomnoofrooms.setText("");
       brooma.setText("");
       bvaletr.setText("");
       bvaletq.setText("");
       bvaleta.setText("");
       btear.setText("");
       bteaq.setText("");
       bteaa.setText("");
       binternetr.setText("");
       binternetq.setText("");
       binterneta.setText("");
       btelephoner.setText("");
       btelephoneq.setText("");
       btelephonea.setText("");
       bnewspaperr.setText("");
       bnewspaperq.setText("");
       bnewspapera.setText("");
       bcarr.setText("");
       bcarq.setText("");
       bcara.setText("");
       blaundryr.setText("");
       blaundryq.setText("");
       blaundrya.setText("");
       bbusr.setText("");
       bbusq.setText("");
       bbusa.setText("");
       bparkr.setText("");
       bparkq.setText("");
       bparka.setText("");
       bparlourr.setText("");
       bparlourq.setText("");
       bparloura.setText("");
       bfooda.setText("");
       btotal.setText("");
    }//GEN-LAST:event_bclearActionPerformed

    private void broomnoofroomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_broomnoofroomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_broomnoofroomsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BILL().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbill;
    private javax.swing.JTextField bbusa;
    private javax.swing.JTextField bbusq;
    private javax.swing.JTextField bbusr;
    private javax.swing.JTextField bcara;
    private javax.swing.JTextField bcarq;
    private javax.swing.JTextField bcarr;
    private javax.swing.JButton bclear;
    private javax.swing.JTextField bfooda;
    private javax.swing.JTextField bguestid;
    private javax.swing.JTextField bguestname;
    private javax.swing.JTextField billno;
    private javax.swing.JTextField binterneta;
    private javax.swing.JTextField binternetq;
    private javax.swing.JTextField binternetr;
    private javax.swing.JTextField blaundrya;
    private javax.swing.JTextField blaundryq;
    private javax.swing.JTextField blaundryr;
    private javax.swing.JTextField bnewspapera;
    private javax.swing.JTextField bnewspaperq;
    private javax.swing.JTextField bnewspaperr;
    private javax.swing.JTextField bparka;
    private javax.swing.JTextField bparkq;
    private javax.swing.JTextField bparkr;
    private javax.swing.JTextField bparloura;
    private javax.swing.JTextField bparlourq;
    private javax.swing.JTextField bparlourr;
    private javax.swing.JButton breturn;
    private javax.swing.JTextField brooma;
    private javax.swing.JTextField broomnoofdays;
    private javax.swing.JTextField broomnoofrooms;
    private javax.swing.JTextField broomr;
    private javax.swing.JTextField bteaa;
    private javax.swing.JTextField bteaq;
    private javax.swing.JTextField btear;
    private javax.swing.JTextField btelephonea;
    private javax.swing.JTextField btelephoneq;
    private javax.swing.JTextField btelephoner;
    private javax.swing.JTextField btotal;
    private javax.swing.JTextField bvaleta;
    private javax.swing.JTextField bvaletq;
    private javax.swing.JTextField bvaletr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
