/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FoodOrder.java
 *
 * Created on Apr 5, 2012, 7:45:32 PM
 */
package miniproj;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Anjana
 */
public class FoodOrder extends javax.swing.JFrame {
Connection con;
Statement stmt;
ResultSet rs;
    /** Creates new form FoodOrder */
    public FoodOrder() {
        initComponents();
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            JOptionPane.showMessageDialog(this, "Driver Loaded Succesfully!");
        }
        catch(ClassNotFoundException E)
        {
                JOptionPane.showMessageDialog(this, "Driver Not Loaded");
        }
        try
        {
            con=DriverManager.getConnection("jdbc:odbc:dsn","system","orcl");
            JOptionPane.showMessageDialog(this, "Connection Established!");
        }
        catch(SQLException E)
        {JOptionPane.showMessageDialog(this, "Connection Not Established");
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        forder = new javax.swing.JButton();
        fclear = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        fguestid = new javax.swing.JTextField();
        freturn = new javax.swing.JButton();
        pb = new javax.swing.JProgressBar();
        fbreak = new javax.swing.JSpinner();
        flunch = new javax.swing.JSpinner();
        fdinner = new javax.swing.JSpinner();
        fcocktail = new javax.swing.JSpinner();
        fchat = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order Food");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GUEST ID");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Breakfast Package");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lunch Puckage");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cocktail Corner");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Chat Mania");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Dinner Package");

        forder.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        forder.setForeground(new java.awt.Color(0, 153, 204));
        forder.setText("ORDER");
        forder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forderActionPerformed(evt);
            }
        });

        fclear.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        fclear.setForeground(new java.awt.Color(0, 153, 204));
        fclear.setText("CLEAR");
        fclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fclearActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Jokerman", 1, 24));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ORDER FOOD");

        fguestid.setForeground(new java.awt.Color(0, 153, 255));
        fguestid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fguestidActionPerformed(evt);
            }
        });

        freturn.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        freturn.setForeground(new java.awt.Color(0, 153, 204));
        freturn.setText("RETURN TO CHECK IN");
        freturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freturnActionPerformed(evt);
            }
        });

        pb.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pbStateChanged(evt);
            }
        });
        pb.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                pbComponentHidden(evt);
            }
        });

        fbreak.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        flunch.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        fdinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        fcocktail.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        fchat.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fbreak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(flunch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fdinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fcocktail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fchat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fguestid, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(301, 301, 301))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(forder)
                                        .addGap(18, 18, 18)
                                        .addComponent(fclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(pb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(freturn, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(319, 319, 319))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel12)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fguestid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fbreak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flunch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fdinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(fcocktail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fchat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forder, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fclear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(freturn)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forderActionPerformed
        // TODO add your handling code here:`
                int i=0;
        try
        {
            String sql=("begin calc_food(1,"+fguestid.getText()+","+fbreak.getToolTipText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            //clear();
            pb.setValue(20);
           i++;
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            String sql=("begin calc_food(2,"+fguestid.getText()+","+flunch.getToolTipText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            //clear();
            pb.setValue(40);
            i++;
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            String sql=("begin calc_food(3,"+fguestid.getText()+","+fdinner.getToolTipText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            //clear();
            pb.setValue(60);
            i++;
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            String sql=("begin calc_food(4,"+fguestid.getText()+","+fcocktail.getToolTipText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            //clear();
            pb.setValue(80);
            i++;
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            String sql=("begin calc_food(5,"+fguestid.getText()+","+fchat.getToolTipText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            //clear();
            pb.setValue(98);
            i++;
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        if(i==5)
        {
            pb.setValue(100);
            JOptionPane.showMessageDialog(this,"Orders updated!!");
        }
}//GEN-LAST:event_forderActionPerformed

    private void fclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fclearActionPerformed
        // TODO add your handling code here:
        fguestid.setText("");
        fbreak.setValue(0);
        flunch.setValue(0);
        fdinner.setValue(0);
        fcocktail.setValue(0);
        fchat.setValue(0);
        
}//GEN-LAST:event_fclearActionPerformed

    private void freturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freturnActionPerformed
        // TODO add your handling code here:
        checkin c = new checkin();
        c.setVisible(true);
        setVisible(false);
}//GEN-LAST:event_freturnActionPerformed

    private void pbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pbStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_pbStateChanged

    private void pbComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pbComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_pbComponentHidden

    private void fguestidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fguestidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fguestidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FoodOrder().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner fbreak;
    private javax.swing.JSpinner fchat;
    private javax.swing.JButton fclear;
    private javax.swing.JSpinner fcocktail;
    private javax.swing.JSpinner fdinner;
    private javax.swing.JTextField fguestid;
    private javax.swing.JSpinner flunch;
    private javax.swing.JButton forder;
    private javax.swing.JButton freturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar pb;
    // End of variables declaration//GEN-END:variables
}
