/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OrderServices.java
 *
 * Created on Apr 5, 2012, 7:46:29 PM
 */
package miniproj;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Anjana
 */
public class OrderServices extends javax.swing.JFrame {
Connection con;
Statement stmt;
ResultSet rs;
    /** Creates new form OrderServices */
    public OrderServices() {
        initComponents();
        try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            JOptionPane.showMessageDialog(this, "Driver Loaded Succesfully!");
        }
        catch(ClassNotFoundException E)
        {
            JOptionPane.showMessageDialog(this, "Driver Not Loaded");
        }
        try
        {
            con=DriverManager.getConnection("jdbc:odbc:dsn","system","orcl");
            JOptionPane.showMessageDialog(this, "Connection Established!");
        }
        catch(SQLException E)
        {
            JOptionPane.showMessageDialog(this, "Connection Not Established");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ouse = new javax.swing.JButton();
        oclear = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        oguestid = new javax.swing.JTextField();
        oreturn = new javax.swing.JButton();
        pb = new javax.swing.JProgressBar();
        ovalet = new javax.swing.JSpinner();
        otea = new javax.swing.JSpinner();
        otelephone = new javax.swing.JSpinner();
        ointernet = new javax.swing.JSpinner();
        onewspaper = new javax.swing.JSpinner();
        ocar = new javax.swing.JSpinner();
        olaundry = new javax.swing.JSpinner();
        obus = new javax.swing.JSpinner();
        opark = new javax.swing.JSpinner();
        oparlour = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Use Service");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GUEST ID");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VALET");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TEA AND COFFEE");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INTERNET");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NEWSPAPER");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CAR SERVICES");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LAUNDRY");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BUS SERVICES");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PARKING");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("BEAUTY PARLOUR");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TELEPHONE");

        ouse.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        ouse.setForeground(new java.awt.Color(0, 153, 204));
        ouse.setText("USE");
        ouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouseActionPerformed(evt);
            }
        });

        oclear.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        oclear.setForeground(new java.awt.Color(0, 153, 204));
        oclear.setText("CLEAR");
        oclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oclearActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("USE SERVICE");

        oguestid.setForeground(new java.awt.Color(0, 153, 255));

        oreturn.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        oreturn.setForeground(new java.awt.Color(0, 153, 204));
        oreturn.setText("RETURN TO CHECK IN");
        oreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oreturnActionPerformed(evt);
            }
        });

        pb.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pbStateChanged(evt);
            }
        });
        pb.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                pbComponentHidden(evt);
            }
        });

        ovalet.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        otea.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        otelephone.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        ointernet.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        onewspaper.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        ocar.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        olaundry.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        obus.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        opark.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        oparlour.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(obus)
                                            .addComponent(olaundry)
                                            .addComponent(ocar)
                                            .addComponent(onewspaper)
                                            .addComponent(otelephone)
                                            .addComponent(ovalet)
                                            .addComponent(otea)
                                            .addComponent(ointernet)
                                            .addComponent(opark)
                                            .addComponent(oparlour, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                            .addComponent(oguestid))
                                        .addGap(55, 55, 55))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(pb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(ouse, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(oclear, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(284, 284, 284))
                            .addComponent(oreturn))
                        .addGap(0, 0, 0))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oguestid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(ovalet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ointernet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onewspaper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ocar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(olaundry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(opark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oparlour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ouse, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oclear))
                .addGap(18, 18, 18)
                .addComponent(oreturn)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-208)/2, (screenSize.height-521)/2, 208, 521);
    }// </editor-fold>//GEN-END:initComponents

    private void ouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouseActionPerformed
        // TODO add your handling code here:`
        int i=0;
        try
        {
            String sql=("begin calc_service(1,"+oguestid.getText()+","+ovalet.getToolTipText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            //clear();
            i++;        
            pb.setValue(10);
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            String sql=("begin calc_service(2,"+oguestid.getText()+","+otea.getToolTipText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            //clear();
            pb.setValue(20);
            i++;
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            String sql=("begin calc_service(3,"+oguestid.getText()+","+otelephone.getToolTipText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            pb.setValue(30);
            //clear();
            i++;
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            String sql=("begin calc_service(4,"+oguestid.getText()+","+ointernet.getToolTipText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            pb.setValue(40);
            //clear();
            i++;
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            String sql=("begin calc_service(5,"+oguestid.getText()+","+onewspaper.getToolTipText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            pb.setValue(50);
            //clear();
            i++;
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            String sql=("begin calc_service(6,"+oguestid.getText()+","+ocar.getToolTipText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            pb.setValue(60);
            //clear();
            i++;
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            String sql=("begin calc_service(7,"+oguestid.getText()+","+olaundry.getToolTipText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            pb.setValue(70);
            //clear();
            i++;
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            String sql=("begin calc_service(8,"+oguestid.getText()+","+obus.getToolTipText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            pb.setValue(80);
            //clear();
            i++;
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            String sql=("begin calc_service(9,"+oguestid.getText()+","+opark.getToolTipText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            pb.setValue(90);
            //clear();
            i++;
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        try
        {
            String sql=("begin calc_service(10,"+oguestid.getText()+","+oparlour.getToolTipText()+"); end;");
            PreparedStatement pstmt=con.prepareCall(sql);
            //JOptionPane.showMessageDialog(this,sql);
            pstmt.execute();
            pb.setValue(99);
            //clear();
            i++;
        } 
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        if(i==10)
        {
            pb.setValue(100);
            JOptionPane.showMessageDialog(this,"Services updated successfully!!");
        }
            
}//GEN-LAST:event_ouseActionPerformed

    private void oclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oclearActionPerformed
        // TODO add your handling code here:
        oguestid.setText("");
        ovalet.setValue(0);
        otea.setValue(0);
        otelephone.setValue(0);
        ointernet.setValue(0);
        onewspaper.setValue(0);
        ocar.setValue(0);
        olaundry.setValue(0);
        obus.setValue(0);
        opark.setValue(0);
        oparlour.setValue(0);
}//GEN-LAST:event_oclearActionPerformed

    private void oreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oreturnActionPerformed
        // TODO add your handling code here:
        checkin c = new checkin();
        c.setVisible(true);
        setVisible(false);
}//GEN-LAST:event_oreturnActionPerformed

    private void pbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pbStateChanged
        // TODO add your handling code here:
}//GEN-LAST:event_pbStateChanged

    private void pbComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pbComponentHidden
        // TODO add your handling code here:
}//GEN-LAST:event_pbComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new OrderServices().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner obus;
    private javax.swing.JSpinner ocar;
    private javax.swing.JButton oclear;
    private javax.swing.JTextField oguestid;
    private javax.swing.JSpinner ointernet;
    private javax.swing.JSpinner olaundry;
    private javax.swing.JSpinner onewspaper;
    private javax.swing.JSpinner opark;
    private javax.swing.JSpinner oparlour;
    private javax.swing.JButton oreturn;
    private javax.swing.JSpinner otea;
    private javax.swing.JSpinner otelephone;
    private javax.swing.JButton ouse;
    private javax.swing.JSpinner ovalet;
    private javax.swing.JProgressBar pb;
    // End of variables declaration//GEN-END:variables
}
